# Run tests against supported Node versions

version: 2.1

orbs:
  node: circleci/node@3.0.0
  browser-tools: circleci/browser-tools@1.1.3

executors:
  node16:
    docker:
      - image: cimg/node:16.1.0-browsers
    working_directory: ~/workspace
  node14:
    docker:
      - image: circleci/node:14-browsers
    working_directory: ~/workspace

jobs:
  test:
    parameters:
      executor:
        type: executor
      coreVersion:
        type: string
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Report Node and Yarn versions
          command: echo "Using Node $(node --version) and Yarn $(yarn --version)"
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install dependencies
          command: yarn install
      - when:
          condition:
            equal: [ "oldest", << parameters.coreVersion >> ]
          steps:
            - run:
                name: Install oldest supported core version
                command: yarn add jasmine-core@$(jq --raw-output '.peerDependencies."jasmine-core"' < package.json | sed 's/\^//')
      - run:
          name: Report core version
          command: echo 'console.log(require("jasmine-core").version())' | node
      - run:
          name: Run tests
          command: yarn test
      - persist_to_workspace:
          root: .
          paths:
            - .

  saucelabs_integration_test:
    executor: node14
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Install Sauce Connect
        command: |
          cd /tmp
          curl https://saucelabs.com/downloads/sc-4.6.4-linux.tar.gz | tar zxf -
          chmod +x sc-4.6.4-linux/bin/sc
          mkdir ~/bin
          cp sc-4.6.4-linux/bin/sc ~/bin
          ~/bin/sc --version
    - run:
        name: Run tests
        command: |
          export PATH=$PATH:$HOME/workspace/bin
          export SAUCE_TUNNEL_IDENTIFIER=$CIRCLE_BUILD_NUM
          export USE_SAUCE=true
          scripts/start-sauce-connect sauce-pidfile
          set +o errexit
          npm test
          exitcode=$?
          set -o errexit
          scripts/stop-sauce-connect $(cat sauce-pidfile)
          exit $exitcode

workflows:
  version: 2
  push: &push_workflow
    jobs:
      - test:
          matrix:
            parameters:
                executor: ["node16", "node14"]
                coreVersion: ["oldest", "newest"]
      - saucelabs_integration_test:
          requires:
            - "test-newest-node14"
          filters:
            branches:
              ignore: /pull\/.*/ # Don't run on pull requests.

  cron:
    <<: *push_workflow
    triggers:
      - schedule:
          # Times are UTC.
          cron: "0 9 * * *"
          filters:
            branches:
               only:
                 - main
